application: pydowntv2
version: 1
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "5d"

builtins:
- appstats: on
- admin_redirect: on
- deferred: on
- remote_api: on

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"

inbound_services:
- warmup

handlers:
- url: /static/favicon.ico #Patch for Warning
  static_files: application/static/img/favicon.ico
  upload: application/static/img/favicon.ico

- url: /favicon.ico
  static_files: application/static/img/favicon.ico
  upload: application/static/img/favicon.ico

- url: /sitemap.xml
  static_files: application/static/sitemap.xml
  upload: application/static/sitemap.xml

- url: /robots.txt
  static_files: application/static/robots.txt
  upload: application/static/robots.txt

- url: /humans.txt
  static_files: application/static/humans.txt
  upload: application/static/humans.txt

- url: /_gae_mini_profiler/static
  static_dir: flaskext/gae_mini_profiler/static

- url: /static
  static_dir: application/static

- url: .*
  script: application.app
